### ISSUE TITLE
Implement data history in Chat Page

### ISSUE THREAD

**Issue by Satyamsharmahp36** [kalviumcommunity/S59_SatyamSharma_StartItUp#62]
There is missing feature in Conversation Page where we have to show the chat history by fetching it from database . 

**Requirements :- ** 

1. Fetch Chat data from database. [Note:- Also Show Date and time for the the question asked]
2. Show data in chat page.

**Comment by ananyatewari** [comment]
Hey

Can I work on this ?

**Comment by Satyamsharmahp36** [comment]
yes sure

**Comment by Satyamsharmahp36** [comment]
Merged Thanks for your contribution
