### ISSUE TITLE
CSS in Chat Page 

### ISSUE THREAD

**Issue by Satyamsharmahp36** [kalviumcommunity/S59_SatyamSharma_StartItUp#63]
There will be question and answer in chat page , but there should CSS in that Pg so that user can differentiate between Question and Answer . 

**Requirements :-**

1. Tailwind CSS should be used for the scalability 
2. Different colours should be used for question and response 
3. Colours and Styling should match with the UI elements of the site

**Comment by ananyatewari** [comment]
Hey

Can I work on this ?

**Comment by Satyamsharmahp36** [comment]
yes , sure start working , But please paste screenshot of UI

**Comment by Satyamsharmahp36** [comment]
Thanks for your contribution
