### ISSUE TITLE
Add Loader in Chat , Feedback , Report and Admin Page . 

### ISSUE THREAD

**Issue by Satyamsharmahp36** [kalviumcommunity/S59_SatyamSharma_StartItUp#64]
As while fetching the data , and doing a post request there is no loader which is added in these pages which creates a lag in the UI experience . So here loader functionality should be added .

**Requirements :-**

1. Your can use any loader like imported form library or add a gif loader or make it with the use of Tailwind CSS
2. Loader should be overlayed over the other components in the pages

**Comment by Swasti008** [comment]
Can I contribute to this issue?

**Comment by Satyamsharmahp36** [comment]
yes sure

**Comment by Swasti008** [comment]
#67 Please review to this PR.

**Comment by Satyamsharmahp36** [comment]
Done, thanks for your contribution
